### ISSUE TITLE
(URGENT) rendering of CalConnect standards identifier

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-calconnect#10]
<img width="595" alt="Screenshot 2021-03-24 at 1 48 42 AM" src="https://user-images.githubusercontent.com/11865/112193655-10f32600-8c43-11eb-9a6c-51e246db5aa7.png">

Should just be CC/DIR, not "csd CC/DIR".

**Comment by andrew2net** [comment]
It isn't a relaton's issue.
