### ISSUE TITLE
Move data to relaton-data-calconnect

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-calconnect#11]
In case using relaton as an API, it's run in an AWS Lambda container. Lambda has a read-only file system and doesn't allow saving files. The callconnect gem fetches and saves the data file with documents.
We need to parse the data file and save the documents as separated files in the GitHub relaton-data-calconnect repository.
@ronaldtse do you agree?

**Comment by ronaldtse** [comment]
Yes can do.

**Comment by andrew2net** [comment]
The `relaton-data-calconnect` has been created. It's used in api.relaton.org. This gem still uses a YAML data file saved in local storage.
